/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.elian_estrada.gui;

import java.awt.Color;
import java.awt.LayoutManager;
import java.awt.Point;

/**
 *
 * @author elian_estrada
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    private boolean flagConsole;
    
    public Home() {
        initComponents();
        this.jScrollPane1.getVerticalScrollBar().setOpaque(true);
        this.jScrollPane1.getVerticalScrollBar().setBackground(new Color(32,32,32));
        this.jScrollPane1.getVerticalScrollBar().setBorder(null);
        this.jScrollPane1.getVerticalScrollBar().setFocusable(false);
        this.jScrollPane1.getVerticalScrollBar().removeAll();
        this.jScrollPane2.setVisible(false);
        this.setSize(1150, this.getSize().height - this.jScrollPane2.getSize().height);
        this.getContentPane().add(this.pnInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 1150, 26 ));
        this.flagConsole = false;
        this.txtConsole.setText("Hola que hace");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        pnMenu = new javax.swing.JPanel();
        lblOpenFile = new javax.swing.JLabel();
        lblNewFile = new javax.swing.JLabel();
        lblSaveFile = new javax.swing.JLabel();
        lblSaveFileAs = new javax.swing.JLabel();
        pnTextArea = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSource = new javax.swing.JTextArea();
        pnInfo = new javax.swing.JPanel();
        lblOutput = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtConsole = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(32, 32, 32));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(32, 32, 32));
        jPanel1.setAutoscrolls(true);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblExit.setBackground(new java.awt.Color(32, 32, 32));
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elian_estrada/images/icons8_Multiply_32px.png"))); // NOI18N
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.setOpaque(true);
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        jPanel1.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 30, 30));

        pnMenu.setBackground(new java.awt.Color(62, 63, 64));
        pnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOpenFile.setBackground(new java.awt.Color(62, 63, 64));
        lblOpenFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elian_estrada/images/icons8-archivo-de-código-40.png"))); // NOI18N
        lblOpenFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpenFile.setOpaque(true);
        lblOpenFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOpenFileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOpenFileMouseExited(evt);
            }
        });
        pnMenu.add(lblOpenFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 40, 50));

        lblNewFile.setBackground(new java.awt.Color(62, 63, 64));
        lblNewFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elian_estrada/images/icons8-más-26.png"))); // NOI18N
        lblNewFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNewFile.setOpaque(true);
        lblNewFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNewFileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNewFileMouseExited(evt);
            }
        });
        pnMenu.add(lblNewFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, -1, 30));

        lblSaveFile.setBackground(new java.awt.Color(62, 63, 64));
        lblSaveFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elian_estrada/images/icons8-guardar-40.png"))); // NOI18N
        lblSaveFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSaveFile.setOpaque(true);
        lblSaveFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSaveFileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSaveFileMouseExited(evt);
            }
        });
        pnMenu.add(lblSaveFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 40, 50));

        lblSaveFileAs.setBackground(new java.awt.Color(62, 63, 64));
        lblSaveFileAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elian_estrada/images/icons8-guardar-como-40.png"))); // NOI18N
        lblSaveFileAs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSaveFileAs.setOpaque(true);
        lblSaveFileAs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSaveFileAsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSaveFileAsMouseExited(evt);
            }
        });
        pnMenu.add(lblSaveFileAs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 40, 50));

        jPanel1.add(pnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 690));

        pnTextArea.setBackground(new java.awt.Color(32, 32, 32));
        pnTextArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setRowHeaderView(null);

        txtSource.setBackground(new java.awt.Color(32, 32, 32));
        txtSource.setColumns(20);
        txtSource.setFont(new java.awt.Font("UKIJ Teng", 0, 14)); // NOI18N
        txtSource.setForeground(new java.awt.Color(255, 255, 255));
        txtSource.setLineWrap(true);
        txtSource.setRows(5);
        txtSource.setTabSize(4);
        txtSource.setWrapStyleWord(true);
        txtSource.setBorder(null);
        txtSource.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(txtSource);

        pnTextArea.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 49, 450, 640));

        jPanel1.add(pnTextArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 450, 690));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, -1));

        pnInfo.setBackground(new java.awt.Color(0, 122, 204));
        pnInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOutput.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblOutput.setForeground(new java.awt.Color(255, 255, 255));
        lblOutput.setText("Output");
        lblOutput.setToolTipText("");
        lblOutput.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOutput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOutputMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOutputMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOutputMouseExited(evt);
            }
        });
        pnInfo.add(lblOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));
        lblOutput.getAccessibleContext().setAccessibleName("lblOutput");

        getContentPane().add(pnInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 972, 1150, 25));

        jScrollPane2.setBorder(null);

        txtConsole.setEditable(false);
        txtConsole.setBackground(new java.awt.Color(32, 32, 32));
        txtConsole.setColumns(20);
        txtConsole.setForeground(new java.awt.Color(255, 255, 255));
        txtConsole.setLineWrap(true);
        txtConsole.setRows(5);
        txtConsole.setWrapStyleWord(true);
        txtConsole.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Console", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtConsole.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(txtConsole);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 1150, 281));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        this.lblExit.setBackground(new Color(60,63,65));
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        this.lblExit.setBackground(new Color(32,32,32));
    }//GEN-LAST:event_lblExitMouseExited

    private void lblOpenFileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpenFileMouseEntered
        this.lblOpenFile.setBackground(new Color(66,67,68));
    }//GEN-LAST:event_lblOpenFileMouseEntered

    private void lblOpenFileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpenFileMouseExited
        this.lblOpenFile.setBackground(new  Color(62,63,64));
    }//GEN-LAST:event_lblOpenFileMouseExited

    private void lblNewFileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewFileMouseEntered
        this.lblNewFile.setBackground(new Color(66,67,68));
    }//GEN-LAST:event_lblNewFileMouseEntered

    private void lblNewFileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewFileMouseExited
        this.lblNewFile.setBackground(new  Color(62,63,64));
    }//GEN-LAST:event_lblNewFileMouseExited

    private void lblSaveFileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveFileMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSaveFileMouseEntered

    private void lblSaveFileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveFileMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSaveFileMouseExited

    private void lblSaveFileAsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveFileAsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSaveFileAsMouseEntered

    private void lblSaveFileAsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveFileAsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSaveFileAsMouseExited

    private void lblOutputMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOutputMouseEntered
        this.lblOutput.setOpaque(true);
        this.lblOutput.setBackground(new Color(60,130,210));
    }//GEN-LAST:event_lblOutputMouseEntered

    private void lblOutputMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOutputMouseExited
        this.lblOutput.setBackground(new Color(0,122,204));
        this.lblOutput.setOpaque(false);
    }//GEN-LAST:event_lblOutputMouseExited

    private void lblOutputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOutputMouseClicked
        if(!this.flagConsole){
            this.setSize(1150, this.getSize().height + this.jScrollPane2.getSize().height);
            this.getContentPane().add(this.pnInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 972, 1150, 26 ));
            this.setLocation(this.getLocation().x, this.getLocation().y - 150);
            this.jScrollPane2.setVisible(true);
            this.flagConsole = true;
        }else{
            this.setSize(1150, this.getSize().height - this.jScrollPane2.getSize().height);
            this.getContentPane().add(this.pnInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 1150, 26 ));
            this.setLocation(this.getLocation().x, this.getLocation().y + 150);
            this.jScrollPane2.setVisible(false);
            this.flagConsole = false;
        }
    }//GEN-LAST:event_lblOutputMouseClicked

   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblNewFile;
    private javax.swing.JLabel lblOpenFile;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblSaveFile;
    private javax.swing.JLabel lblSaveFileAs;
    private javax.swing.JPanel pnInfo;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnTextArea;
    private javax.swing.JTextArea txtConsole;
    private javax.swing.JTextArea txtSource;
    // End of variables declaration//GEN-END:variables
}
