
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package com.elian_estrada.analyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAVDER = 8;
  public static final int DIGIT = 18;
  public static final int DECIMAL = 19;
  public static final int RANG = 10;
  public static final int KLEAN = 12;
  public static final int COMDOBLE = 27;
  public static final int PARIZQ = 5;
  public static final int DOSPUN = 4;
  public static final int CONCAT = 14;
  public static final int PARDER = 6;
  public static final int UMENOS = 20;
  public static final int DISYN = 15;
  public static final int PORCENT = 11;
  public static final int POS = 13;
  public static final int LETTER = 24;
  public static final int COMA = 3;
  public static final int SIMBOLS = 28;
  public static final int EOF = 0;
  public static final int CADENA_TEXTO = 22;
  public static final int COMILLA = 26;
  public static final int CONJ = 21;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 23;
  public static final int BOOL = 16;
  public static final int ENTERO = 17;
  public static final int NLINE = 25;
  public static final int ASIG = 9;
  public static final int LLAVIZQ = 7;
  public static final int PTCOMA = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "COMA",
  "DOSPUN",
  "PARIZQ",
  "PARDER",
  "LLAVIZQ",
  "LLAVDER",
  "ASIG",
  "RANG",
  "PORCENT",
  "KLEAN",
  "POS",
  "CONCAT",
  "DISYN",
  "BOOL",
  "ENTERO",
  "DIGIT",
  "DECIMAL",
  "UMENOS",
  "CONJ",
  "CADENA_TEXTO",
  "IDENTIFICADOR",
  "LETTER",
  "NLINE",
  "COMILLA",
  "COMDOBLE",
  "SIMBOLS"
  };
}

